### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/accessibility-fixer-upper#1]
@muxlowc

I'm stuck with finding some of the errors, because when I put it through mark bot I'm not sure to what it is referring to.

**Comment by MacKenzieRose** [comment]
Hi @AlexanderTahtadjian 

Which Markbot errors are causing confusion?

Cheers!
MacKenzie

**Comment by AlexanderTahtadjian** [comment]
@MacKenzieRose 
Its these Markbot errors that are causing confusion. I've been trying to figure them out but I'm not entirely sure what they mean?
![Annotation 2020-04-05 102516](https://user-images.githubusercontent.com/55193211/78501159-72676f80-7728-11ea-85b4-ae319c9083d9.png)
![Annotation 2020-04-05 102553](https://user-images.githubusercontent.com/55193211/78501160-73000600-7728-11ea-8df1-0b922aa5cfbb.png)
![Annotation 2020-04-05 102630](https://user-images.githubusercontent.com/55193211/78501161-73000600-7728-11ea-9639-f0a9feb93923.png)
![Annotation 2020-04-05 102708](https://user-images.githubusercontent.com/55193211/78501162-73000600-7728-11ea-887c-f5d3393418be.png)
![Annotation 2020-04-05 102738](https://user-images.githubusercontent.com/55193211/78501163-73989c80-7728-11ea-8be8-3178b54e6961.png)

**Comment by muxlowc** [comment]
@AlexanderTahtadjian @MacKenzieRose 

Hey Alex - quite a few people are struggling with this one. If you can put this one aside for now, I'm going to go through this assignment to explain the concepts again after lecture this week. I think it will be easier to explain everything again through video chat, and that why I can explain to a bunch of people at the same time - sound good?

**Comment by AlexanderTahtadjian** [comment]
@muxlowc 

Ok, I'll try the one with the treasure one since its just fixing the mistakes as well.
